<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class UserEditRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        if (request()->password){
            return [
                'last_name'=>'required|max:10|unique:users,last_name,'.request()->id,
                'email'=>'required|email|unique:users,email,'.request()->id,
                'confirm_password' => 'required|same:password'
            ];
        }
        return [
            'last_name'=>'required|max:10|unique:users,name,'.request()->id,
            'email'=>'required|email|unique:users,email,'.request()->id,
        ];
    }

    public function messages()
    {
        return [
            'name.required' => 'Trường tên không được để trống',
            'name.unique' => "Tên $this->last_name đã tồn tại",
            'email.required' => 'Trường email không được để trống',
            'email.unique' => "Tên $this->email đã tồn tại",
            'confirm_password.required' => 'Vui long nhap lại mật khẩu',
            'confirm_password.same' => 'Mật khẩu xác nhận không đúng'
        ]; // TODO: Change the autogenerated stub

    }
}
